export const words = {
  // RH et postes
  "directeur financier": "CFO",
  "chef de service": "head of department",
  "responsable administratif": "office manager",
  "chef de magasin": "floor manager",
  "chargé de clientèle": "account manager",
  "équipe de maintenance": "maintenance crew",
  "informaticien": "IT technician",
  "assistant de direction": "personnal assistant",
  "employé de bureau": "office clerk",
  "cadre": "executive",
  "intérimaire": "temp",
  "demandeur d'emploi": "job seeker",
  "prestataire": "contractor",
  "stagiaire": "intern",
  "agent de sécurité": "security guard",
  "commercial": "sales rep",
  "employé": "clerk",
  "graphiste": "graphic designer",
  
  // Recrutement et carrière
  "CV": "resume",
  "poste vacant": "vacancy",
  "agence d'intérim": "temp agency",
  "évaluation": "assessment",
  "estimation / expertise": "appraisal",
  "présence du personnel": "staff attendance",
  "congé": "leave",
  "main d'œuvre": "manpower",
  "mutation": "transfer",
  "poser sa candidature": "to apply",
  "fournir une référence": "to provide a reference",
  "évaluer": "to assess",
  "être sur la liste": "to be shortlisted",
  "embaucher": "to hire",
  "nommer": "to appoint",
  "pointer": "to clock in",
  "réduire les effectifs": "to downsize",
  "licencier": "to dismiss",
  "renvoyer": "to fire",
  "donner son préavis": "to give notice",
  "démissionner": "to resign",
  
  // Contrat et salaire
  "période d'essai": "trial period",
  "à plein temps": "full time",
  "à temps partiel": "part time",
  "bulletin de paie": "pay slip",
  "salaire": "salary",
  "salaire horaire": "hourly wage",
  "heures supplémentaires": "overtime",
  "augmentation": "increase",
  "motivation": "incentive",
  "avantages": "benefits",
  "bénévole": "volunteer",
  "à son compte": "freelance",
  "accord": "agreement",
  "avenant": "amendment",
  "partie": "party",
  "qui lie": "binding",
  "ci-dessous": "hereunder",
  "par lequel": "whereby",
  "conforme": "abide by",
  "avoir droit": "to be eligible",
  
  // Vie d'entreprise
  "employé du mois": "employee of the month",
  "promotion": "promotion",
  "planning": "schedule",
  "ordre du jour": "agenda",
  "compte-rendu": "minutes",
  "congrès": "convention",
  "sortie": "outing",
  "participant": "attendee",
  "collecte de fonds": "fundraising",
  "retraite": "retirement",
  "pot de départ": "retirement reception",
  "tenir une reunion": "to hold a meeting",
  "organiser une reunion": "to arrange a meeting",
  "avoir lieu": "to take place",
  "mener": "to lead",
  "reprendre": "to resume",
  "reporter": "to postpone",
  "présider": "to chair",
  "président": "chairman",
  
  // Magasin
  "magasin": "store",
  "centre commercial": "mall",
  "employé de magasin": "store clerk",
  "caissier": "cashier",
  "fidélité": "loyalty",
  "allée": "aisle",
  "chariot": "cart",
  "caisse paiement": "checkout",
  "ticket de caisse": "receipt",
  "monnaie": "change",
  "bon de réduction": "coupon",
  "soldes": "sales",
  "réduction": "markdown",
  "appareil électroménager": "household appliance",
  "produits laitiers": "dairy products",
  "fruits et légumes": "produce",
  "exposer": "to display",
  "présentoir": "display",
  
  // Commerce
  "marchandise": "goods",
  "article": "item",
  "stock": "stock",
  "fournisseur": "supplier",
  "détaillant": "retailer",
  "grossiste": "wholesaler",
  "acheteur": "purchaser",
  "devis": "quote",
  "garantie": "warranty",
  "service après-vente": "after sales service",
  "lot": "batch",
  "date limite": "deadline",
  "remise": "rebate",
  "défectueux": "defective",
  "offert": "complimentary",
  "remboursement": "refund",
  "rembourser": "to refund",
  "passer commande": "to place an order",
  "retourner": "to return",
  
  // Facturation
  "facture": "invoice",
  "facturer": "to invoice",
  "addition": "bill",
  "modalités de paiement": "terms of payment",
  "en-tête": "letterhead",
  "créancier": "creditor",
  "port et manutention": "shipping and handling",
  "unités": "units",
  "somme due": "amount due",
  "petits caractères": "fine print",
  "frais": "fees",
  "rappel": "reminder",
  "amende": "fine",
  "émettre de la chaleur": "to emit heat",
  "émettre un rapport": "to issue a report",
  "payable": "payable",
  "en attente": "pending",
  "nul": "void",
  "impayé": "unpaid",
  "dans les 20 jours": "within 20 days",
  "ne pas tenir compte": "to disregard",
  
  // Livraison
  "transporteur": "carrier",
  "coursier": "courier",
  "destinataire": "recipient",
  "employé de la poste": "postal worker",
  "entrepôt": "warehouse",
  "stockage": "storage",
  "caisse en bois": "crate",
  "colis": "package",
  "emballer": "to pack",
  "pile": "stack",
  "empiler": "to stack",
  "chargement": "loading",
  "charger": "to load",
  "expédition": "shipment",
  "fret": "freight",
  "chariot élévateur": "forklift truck",
  "frais d'envoi en express": "rush fees",
  "en 24 heures": "overnight",
  "peser": "to weigh",
  "expédier": "to dispatch",
  "déposer quelqu'un": "to drop off",
  "passer prendre": "to pick up"
};
