export const words = {
  // Travel for work
  "trajet": "journey",
  "aller simple": "one way",
  "aller-retour": "round trip",
  "transports en commun": "public transportation",
  "quai": "platform",
  "voie (de chemin de fer)": "track",
  "annonce": "announcement",
  "tableau d'affichage": "board",
  "taxi": "taxi",
  "embouteillage": "traffic jam",
  "heure de pointe": "rush hour",
  "voie (sur route)": "lane",
  "péage": "toll",
  "salon professionnel": "trade show",
  "attraper": "catch",
  "manquer": "miss",
  "héler": "hail",
  "covoiturage": "carpool",
  "trajet maison-travail": "commute",

  // Air travel
  "compagnie aérienne": "airline",
  "carte d'embarquement": "boarding pass",
  "pièce d'identité": "ID",
  "douane": "customs",
  "porte d'embarquement": "gate",
  "bagage à main": "carry-on",
  "hôtesse de l'air": "flight attendant",
  "compartiment supérieur": "overhead bin",
  "couloir": "aisle",
  "tablette": "tray table",
  "piste": "runway",
  "retardé": "delayed",
  "annulé": "cancelled",
  "arrivée des bagages": "baggage claim",
  "passer prendre": "pick up",
  "attacher": "fasten",
  "retirer": "remove",
  "dépasser": "exceed",
  "décoller": "take off",
  "enregistrement": "check in",

  // Hotels
  "client": "guest",
  "hall d'entrée": "lobby",
  "réception": "front desk",
  "tarif": "rate",
  "compris": "included",
  "bagagiste": "porter",
  "ascenseur": "elevator",
  "clé magnétique": "keycard",
  "service de chambre": "room service",
  "femme de chambre": "housekeeper",
  "serviette douche": "towel",
  "couverture": "blanket",
  "oreiller": "pillow",
  "équipements": "amenities",
  "bien situé": "convenient",
  "vue": "view",
  "navette": "shuttle",
  "réserver": "book",
  "quitter": "vacate",
  "régler sa note": "check out",

  // Car rental
  "agence de location": "rental agency",
  "parc de véhicules": "fleet of vehicles",
  "permis de conduire": "driver's license",
  "politique": "policy",
  "automatique": "automatic",
  "4x4": "four-wheel drive",
  "carburant": "fuel",
  "réservoir": "tank",
  "pare-brise": "windshield",
  "volant": "steering wheel",
  "tableau de bord": "dashboard",
  "coffre": "trunk",
  "pneu": "tire",
  "siège auto": "car seat",
  "économique": "economy",
  "freiner": "brake",
  "marche arrière": "reverse",
  "faire le plein": "fill",
  "tomber en panne": "break down",
  "préparer pour l'hiver": "winterize",

  // Entertainment (visits)
  "matinée": "matinee",
  "cinéma": "movie theater",
  "la distribution": "cast",
  "réalisateur": "director",
  "intrigue": "plot",
  "personnage": "character",
  "théâtre": "theater",
  "pièce de théâtre": "play",
  "entracte": "intermission",
  "projection": "showing",
  "exposition": "exhibition",
  "vernissage": "opening",
  "œuvre d'art": "work of art",
  "tableau": "painting",
  "sculpteur": "sculptor",
  "critique": "review",
  "suite": "sequel",
  "être à l'affiche": "star",
  "tourner": "shoot",

  // Restaurants
  "serveur": "waiter",
  "nappe": "tablecloth",
  "serviette table": "napkin",
  "plat": "dish",
  "couverts": "cutlery",
  "pourboire": "tip",
  "addition": "check",
  "libre-service": "self-service",
  "traiteur": "caterer",
  "boisson": "beverage",
  "entrée": "appetizer",
  "plat principal": "main course",
  "client d'un restaurant": "patron / diner",
  "fruits de mer": "seafood",
  "sain": "wholesome",
  "à emporter": "take-out",
  "pétillant": "sparkling",
  "savoureux": "tasty",
  "recommander": "recommend",

  // Vacations
  "crème solaire": "sunscreen",
  "hébergement chez l'habitant sur canape": "couch surfing",
  "serviette de plage": "beach towel",
  "station balnéaire": "resort",
  "lunettes de soleil": "sunglasses",
  "agent de voyage": "travel agent",
  "itinéraire": "itinerary",
  "tourisme": "sightseeing",
  "croisière": "cruise",
  "plage": "beach",
  "valise": "suitcase",
  "logement": "accommodation",
  "vacancier": "vacationer",
  "habitant": "local",
  "vacances en tente": "camping trip",
  "tout compris": "all-inclusive",
  "faire les bagages": "pack",
  "bronzer": "sunbathe",
  "s'échapper": "get away",
  "satisfaire les besoins": "cater to",

  // Leisure
  "jeu de société": "board game",
  "travaux manuels": "crafts",
  "jogging": "jogging",
  "échecs": "chess",
  "cyclisme": "cycling",
  "jardinage": "gardening",
  "bricolage": "DIY",
  "parc d'attractions": "amusement park",
  "randonnée": "hike",
  "voile": "sailing",
  "reposant": "relaxing",
  "abonnement": "season ticket",
  "attraction touristique": "attraction",
  "couture": "sewing",
  "intérieur": "indoor",
  "collectionner": "collect",
  "s'inscrire à": "enroll in",
  "manger au restaurant": "eat out",
  "faire du sport": "work out",
  "sortie": "outing",

  // Doctor
  "médecin": "physician",
  "infirmier": "nurse",
  "mutuelle": "health insurance",
  "reste a charge": "co-pay",
  "médicaments": "medication",
  "comprimé": "tablet",
  "ordonnance": "prescription",
  "épidémie": "outbreak",
  "rendez-vous": "appointment",
  "bilan de santé": "checkup",
  "maladie": "illness",
  "blessure": "injury",
  "mal de tête": "headache",
  "tension artérielle": "blood pressure",
  "cabinet médical": "practice",
  "arrêt maladie": "sick leave",
  "service hospitalier": "ward",
  "consulter": "consult",
  "rechute": "relapse",

  // Health (professionals)
  "opticien": "optician",
  "la vue": "eyesight",
  "fatigue visuelle": "eyestrain",
  "monture": "frame",
  "verres": "lenses",
  "lunettes": "eyeglasses",
  "dentiste": "dentist",
  "fraise": "drill",
  "carie": "cavity",
  "assistant dentaire": "dental hygienist",
  "praticien": "medical practitioner",
  "kinésithérapie": "physical therapy",
  "chirurgien": "surgeon",
  "bloc opératoire": "operating theater",
  "urgences": "emergency services",
  "diététicien": "dietician",
  "chercheur": "researcher",
  "conseiller": "advise",
  "envoyer vers un spécialiste": "refer to",

  // Pharmacy
  "pharmacie": "drugstore",
  "en vente libre": "over-the-counter",
  "effets secondaires": "side effects",
  "notice": "leaflet",
  "posologie": "dosage",
  "étagère": "shelf",
  "interaction": "interaction",
  "découverte majeure": "breakthrough",
  "ventre vide": "empty stomach",
  "avertissement": "warning",
  "traitement": "treatment",
  "nuisible": "harmful",
  "puissant": "potent",
  "enflé": "swollen",
  "de près": "closely",
  "délivrer une ordonnance": "fill a prescription",
  "soulager": "relieve",
  "soigner": "treat",
  "appliquer": "apply",

  // Healthy living
  "endurance": "stamina",
  "bien-être": "well-being",
  "quotidien": "daily",
  "rampe": "ramp",
  "adaptations": "accommodations",
  "malbouffe": "junk food",
  "alimentation équilibrée": "balanced diet",
  "sport d'équipe": "team sport",
  "régime spécifique": "special diet",
  "absentéisme": "absenteeism",
  "risque pour la santé": "health hazard",
  "médecin du travail": "occupational health doctor",
  "psychothérapie": "counseling",
  "résilient": "resilient",
  "dégradé": "impaired",
  "sain (bon pour la santé)": "healthful",
  "en bonne santé": "healthy",
  "nutritif": "nutritious",
  "ergonomique": "ergonomic",
  "garder la forme": "keep fit",
};