
export const management = {
  // Acronymes fondamentaux
  "QCD": "Qualité Coûts Délais",
  "MOA": "Maîtrise d'Ouvrage",
  "MOE": "Maîtrise d'Œuvre",
  "WBS": "Work Breakdown Structure",
  "PMI": "Project Management Institute",
  "PMO": "Project Management Office",
  "REX": "Retour d'Expérience",
  
  // Matrice SWOT et variantes
  "SWOT": "Strengths Weaknesses Opportunities Threats",
  "S": "Strengths - Forces",
  "W": "Weaknesses - Faiblesses",
  "O": "Opportunities - Opportunités",
  "T": "Threats - Menaces",
  "FFOM": "Forces Faiblesses Opportunités Menaces",
  "FFOR": "Forces Faiblesses Opportunités Risques",
  "MOFF": "Menaces Opportunités Forces Faiblesses",
  "AFOM": "Atouts Faiblesses Opportunités Menaces",
  
  // Cycle PDCA et variantes
  "PDCA": "Plan Do Check Act",
  "Plan": "Planifier - Préparer",
  "Do": "Développer - Réaliser",
  "Check": "Contrôler - Vérifier",
  "Act": "Ajuster - Améliorer",
  "PDSA": "Plan Do Study Act",
  "OPDCA": "Observe Plan Do Check Act",
  "DMAIC": "Define Measure Analyze Improve Control",
  "cycle de Shewhart": "PDCA",
  "cycle de Deming": "PDSA",
  
  // Objectifs SMART
  "SMART": "Spécifique Mesurable Accepté Réaliste Temporel",
  "Spécifique": "simple, précis et clair",
  "Mesurable": "quantifiable et vérifiable",
  "Accepté": "négocié et approprié par l'acteur",
  "Réaliste": "ambitieux mais atteignable",
  "Temporel": "défini dans le temps avec échéance",
  
  // Matrice RACI et variantes
  "RACI": "Réalise Autorité Consulté Informé",
  "R": "Réalise - Responsible",
  "A": "Autorité - Accountable",
  "C": "Consulté - Consulted",
  "I": "Informé - Informed",
  "PARIS": "Participant Accountable Responsible Informed Sign-off",
  "RASCI": "Responsible Accountable Support Consulted Informed",
  "RACI-VS": "Responsible Accountable Consulted Informed Verify Sign",
  "CAIRO": "Consulted Accountable Informed Responsible Omitted",
  "RAPID": "Recommend Agree Perform Input Decide",
  
  // Méthode QQOQCCP
  "QQOQCCP": "Qui Quoi Où Quand Comment Combien Pourquoi",
  "Qui": "acteurs concernés",
  "Quoi": "objet et action",
  "Où": "lieu",
  "Quand": "moment et durée",
  "Comment": "moyens et méthode",
  "Combien": "quantité et coût",
  "Pourquoi": "raison et objectif",
  
  // Outils d'analyse
  "Ishikawa": "diagramme causes-effet en arêtes de poisson",
  "diagramme causes-effet": "Ishikawa",
  "5 pourquoi": "méthode recherche cause racine par questions successives",
  "arbre des causes": "diagramme causal hiérarchique",
  "Pareto": "loi des 80/20",
  "principe de Pareto": "20% des causes produisent 80% des effets",
  "80/20": "principe de Pareto",
  "diagramme de Pareto": "graphique causes par ordre décroissant",
  
  // Matrice d'Eisenhower
  "Eisenhower": "matrice urgent/important",
  "matrice Eisenhower": "classification tâches selon urgence et importance",
  "urgent et important": "à exécuter immédiatement",
  "important non urgent": "à planifier",
  "urgent non important": "à déléguer",
  "ni urgent ni important": "à éliminer",
  
  // Méthodes agiles
  "méthodes agiles": "approche itérative et incrémentale",
  "SCRUM": "méthode agile avec sprints",
  "XP": "Extreme Programming",
  "DSDM": "Dynamic Systems Development Method",
  "Lean startup": "méthode agile création entreprise",
  "sprint": "cycle court de développement 1-4 semaines",
  "backlog": "liste priorisée des besoins clients",
  "product backlog": "liste complète fonctionnalités souhaitées",
  "release": "version livrée du produit",
  "timebox": "boîte de temps fixe",
  "itération": "cycle de développement répété",
  "incrément": "ajout fonctionnel progressif",
  "approche incrémentale": "livraison par versions successives",
  "approche itérative": "amélioration par cycles répétés",
  
  // Gestion des risques - Normes
  "ISO 31000": "norme internationale gestion des risques",
  "criticité": "gravité multipliée par fréquence",
  "gravité": "impact ou conséquences si risque se réalise",
  "fréquence": "probabilité occurrence du risque",
  "impact": "conséquences du risque",
  "probabilité": "chance qu'événement survienne",
  "menace": "événement potentiel négatif",
  "risque": "menace quantifiée en gravité et fréquence",
  "incertitude": "situation sans probabilités connues",
  "aléa": "événement imprévisible",
  
  // Stratégies gestion des risques
  "protection": "réduire la gravité du risque",
  "évitement": "réduire la fréquence du risque",
  "transfert": "reporter risque sur tiers ou assurance",
  "acceptation": "assumer le risque consciemment",
  "mitigation": "réduire impact ou probabilité",
  "plan de prévention": "ensemble mesures anticiper risques",
  "plan B": "plan de secours si problème survient",
  "plan de contingence": "plan B",
  "mesure organisationnelle": "changement organisation pour réduire risque",
  "mesure juridique": "clause contrat pour protéger",
  "mesure financière": "réserve budget pour imprévus",
  
  // Types de risques
  "risque de gravité": "rare mais conséquences catastrophiques",
  "risque de fréquence": "fréquent mais impact faible",
  "risque négligeable": "rare et sans conséquences",
  "risque intolérable": "fréquent et grave - à éviter absolument",
  "risque prioritaire": "criticité élevée",
  "risque résiduel": "risque restant après mesures",
  "cause racine": "origine profonde du problème",
  
  // Concepts fondamentaux projet
  "projet": "action temporaire pour résultat unique",
  "gestion de projet": "application connaissances pour atteindre objectifs",
  "management de projet": "gestion de projet",
  "livrable": "produit service ou résultat fourni",
  "jalon": "événement marquant étape importante",
  "milestone": "jalon",
  "étape": "phase délimitée par jalons",
  "phase": "période projet avec activités homogènes",
  "lot de travail": "ensemble tâches assigné à responsable unique",
  "work package": "lot de travail",
  "tâche": "travail élémentaire à réaliser",
  "activité": "ensemble de tâches",
  "contrainte": "limitation imposée au projet",
  "délai": "temps imparti pour réalisation",
  "échéance": "date limite absolue",
  "deadline": "date butoir",
  "date butoir": "échéance impérative",
  "planning": "calendrier prévisionnel du projet",
  "calendrier": "planning",
  "avancement": "progression du projet",
  "déroulement": "succession étapes du projet",
  "clôture": "fin officielle du projet",
  
  // Triangle QCD
  "triangle QCD": "Qualité Coûts Délais",
  "Scope Time Cost": "Qualité Délais Coûts en anglais",
  "qualité": "spécifications et périmètre du livrable",
  "coût": "budget et ressources financières",
  "délais": "temps pour livraison",
  "Time": "délais",
  "Cost": "coûts",
  "Scope": "périmètre qualité",
  "périmètre": "étendue et limites du projet",
  "budget": "ressources financières allouées",
  "cahier des charges": "document spécifications techniques",
  "spécifications": "description détaillée attendus",
  "spécifications techniques": "exigences techniques détaillées",
  "fonctions": "capacités du livrable",
  "fiabilité": "capacité fonctionner sans défaillance",
  
  // Acteurs projet
  "chef de projet": "responsable coordination et pilotage",
  "project manager": "chef de projet",
  "maître d'ouvrage": "demandeur et propriétaire final",
  "project owner": "maître d'ouvrage",
  "maître d'œuvre": "réalisateur technique du projet",
  "project contractor": "maître d'œuvre",
  "partie prenante": "acteur concerné par le projet",
  "stakeholder": "partie prenante",
  "commanditaire": "demandeur initial du projet",
  "client": "bénéficiaire final du livrable",
  "équipe projet": "personnes travaillant sur le projet",
  "équipe-projet": "équipe projet",
  "prestataire": "entreprise externe fournissant service",
  "sous-traitant": "entreprise réalisant partie du projet",
  "sponsor": "garant stratégique du projet",
  "comité de pilotage": "instances décisionnelles du projet",
  "COPIL": "comité de pilotage",
  "steering committee": "comité de pilotage",
  "coordinateur": "personne harmonisant sans autorité",
  "coordinateur de projet": "chef de projet en matriciel faible",
  "responsable": "personne ayant autorité sur tâche",
  "directeur de projet": "niveau hiérarchique au-dessus chef projet",
  "utilisateurs finaux": "personnes utilisant le livrable",
  "riverains": "parties prenantes externes impactées",
  "communauté": "ensemble parties prenantes externes",
  "bailleur de fonds": "organisme finançant le projet",
  
  // Organisation et structures
  "organigramme": "représentation structure organisation",
  "structure matricielle": "organisation double rattachement",
  "structure fonctionnelle": "organisation par métiers",
  "structure de projet": "équipe dédiée détachée",
  "matriciel faible": "coordinateur sans pouvoir hiérarchique",
  "matriciel fort": "chef projet même poids que directeurs",
  "matriciel équilibré": "autorité partagée équilibrée",
  "projet transversal": "implique plusieurs services",
  "projet local": "au sein d'un seul service",
  "projet sorti": "équipe détachée à temps plein",
  "joint venture": "co-entreprise entre partenaires",
  "co-entreprise": "joint venture",
  "gouvernance": "système circulation info et décisions",
  "hiérarchie": "ligne de commandement",
  "service": "département fonctionnel",
  "département": "service",
  "direction": "niveau stratégique organisation",
  "direction générale": "plus haut niveau décisionnel",
  "direction métier": "responsable domaine fonctionnel",
  
  // Documents projet
  "charte de projet": "acte naissance officiel du projet",
  "project charter": "charte de projet",
  "lettre de mission": "document confiant responsabilité chef projet",
  "note de cadrage": "document définissant périmètre projet",
  "fiche de définition": "document synthèse projet",
  "compte-rendu": "synthèse écrite réunion",
  "minutes": "compte-rendu",
  "ordre du jour": "liste sujets à traiter en réunion",
  "agenda": "ordre du jour",
  "rapport": "document état avancement",
  "rapport d'avancement": "synthèse progression projet",
  "documentation": "ensemble documents projet",
  "procès-verbal": "compte-rendu officiel",
  "executive summary": "résumé direction synthétique",
  "business case": "justification économique du projet",
  "cas d'affaires": "business case",
  
  // Cycle de vie projet
  "cycle de vie": "ensemble phases de la conception à la clôture",
  "cycle de projet": "cycle de vie",
  "définition": "phase établissement objectifs",
  "montage": "phase préparation détaillée",
  "exécution": "phase réalisation concrète",
  "cadrage": "définition périmètre et objectifs",
  "lancement": "démarrage officiel du projet",
  "pilotage": "suivi et contrôle avancement",
  "livraison": "remise livrable au client",
  "mise en production": "démarrage utilisation livrable",
  "post-mortem": "réunion retour expérience fin projet",
  "retour d'expérience": "analyse succès et échecs",
  "bilan de projet": "synthèse résultats obtenus",
  "leçons apprises": "enseignements tirés du projet",
  "capitalisation": "conservation et partage connaissance",
  
  // Planification
  "diagramme de Gantt": "planning barres horizontales",
  "Gantt": "diagramme de Gantt",
  "séquencement": "détermination ordre des tâches",
  "enchaînement": "succession logique des tâches",
  "dépendance": "lien entre tâches",
  "chemin critique": "séquence tâches déterminant durée minimale",
  "tâche critique": "tâche sur le chemin critique",
  "marge": "délai disponible sans retarder projet",
  "marge libre": "délai sans impacter tâche suivante",
  "marge totale": "délai sans impacter fin projet",
  "jalonnement": "découpage en étapes intermédiaires",
  "charge de travail": "temps-homme nécessaire",
  "workload": "charge de travail",
  "jour-homme": "unité charge travail une personne un jour",
  "temps-homme": "unité charge de travail",
  "durée": "temps calendaire de la tâche",
  "effort": "charge de travail nécessaire",
  "ressource": "moyen humain technique ou financier",
  "affectation": "attribution ressource à tâche",
  "disponibilité": "temps où ressource est libre",
  
  // Coûts et budget
  "coût global": "somme tous coûts du cycle de vie",
  "coût d'investissement": "coût unique au démarrage",
  "coût de développement": "coût variable de réalisation",
  "coût d'utilisation": "coût exploitation du livrable",
  "coût d'exploitation": "coût utilisation",
  "coût de maintenance": "coût entretien du livrable",
  "coût d'extinction": "coût fin de vie et recyclage",
  "coût fixe": "coût indépendant du volume",
  "coût variable": "coût proportionnel au volume",
  "amortissement": "répartition coût investissement dans temps",
  "trésorerie": "disponibilités financières",
  "cash flow": "flux de trésorerie",
  "dépense": "sortie financière",
  "revenu": "entrée financière",
  "chiffre d'affaires": "revenus des ventes",
  "rentabilité": "rapport bénéfices sur coûts",
  "retour sur investissement": "gain par rapport investissement initial",
  "ROI": "Return On Investment",
  "manque à gagner": "perte revenu potentiel",
  "coût de revient": "coût total de production",
  "réserve budgétaire": "budget mis de côté pour imprévus",
  
  // Types de ressources
  "ressources humaines": "personnel et compétences",
  "ressources techniques": "matériel et équipements",
  "ressources financières": "budget et trésorerie",
  "ressources temporelles": "temps disponible",
  "compétence": "capacité réaliser tâche spécifique",
  "expertise": "compétence approfondie domaine",
  "polyvalence": "capacité assumer plusieurs rôles",
  "force de travail": "capacité production équipe",
  "effectifs": "nombre de personnes",
  "main d'œuvre": "personnel travaillant sur projet",
  "personnel": "ensemble collaborateurs",
  
  // Réunions
  "réunion technique": "résolution problèmes spécifiques",
  "réunion de chantier": "présentation avancement au COPIL",
  "réunion d'avancement": "suivi interne équipe projet",
  "stand-up meeting": "point rapide debout quotidien",
  "daily stand-up": "réunion debout quotidienne",
  "soutenance": "présentation formelle de rapport",
  "brainstorming": "séance créativité collective",
  "atelier": "réunion travail collaboratif",
  "workshop": "atelier",
  "séminaire": "réunion longue hors site",
  "kick-off": "réunion lancement projet",
  "revue": "réunion validation livrable",
  "comité": "réunion décisionnelle",
  
  // Outils de travail collaboratif
  "todo list": "liste tâches à faire",
  "liste de tâches": "todo list",
  "pilote action délai": "responsable tâche échéance",
  "PAD": "Pilote Action Délai",
  "flip chart": "paper-board",
  "paper-board": "tableau feuilles mobiles",
  "mind map": "carte mentale",
  "carte mentale": "mind map",
  "carte heuristique": "mind map",
  
  // Validation et contrôle
  "validation": "approbation conformité aux exigences",
  "vérification": "contrôle technique spécifications",
  "recette": "validation finale par client",
  "homologation": "validation réglementaire officielle",
  "test": "vérification fonctionnement",
  "contrôle qualité": "vérification conformité standards",
  "audit": "examen méthodique et indépendant",
  "revue de projet": "examen formel avancement",
  "inspection": "examen détaillé livrable",
  
  // Indicateurs et mesures
  "KPI": "Key Performance Indicator",
  "indicateur": "mesure performance",
  "indicateur clé": "KPI",
  "métrique": "mesure quantitative",
  "taux d'avancement": "pourcentage réalisé",
  "pourcentage avancement": "taux avancement",
  "écart": "différence entre prévu et réalisé",
  "dérive": "écart croissant par rapport objectifs",
  "retard": "écart temps négatif",
  "avance": "écart temps positif",
  "surcoût": "dépassement budget",
  "économie": "coût inférieur au prévu",
  "performance": "niveau atteinte objectifs",
  
  // Effet tunnel et problèmes
  "effet tunnel": "absence visibilité sur avancement",
  "tunnel": "effet tunnel",
  "opacité": "manque transparence",
  "rétention information": "non partage informations",
  "silo": "cloisonnement entre services",
  "goulot étranglement": "point blocage ralentissant projet",
  "bottleneck": "goulot étranglement",
  "blocage": "impossibilité avancer",
  "problème": "difficulté à résoudre",
  "difficulté": "obstacle rencontré",
  "crise": "situation problématique grave",
  
  // Livrables intermédiaires
  "prototype": "version test préliminaire",
  "maquette": "représentation simplifiée",
  "POC": "Proof Of Concept",
  "preuve de concept": "POC",
  "pilote": "version test échelle réduite",
  "version beta": "version test quasi finale",
  "MVP": "Minimum Viable Product",
  "produit minimum viable": "MVP",
  "version": "état donné du livrable",
  "livraison intermédiaire": "livrable étape",
  
  // Profil de projet
  "profil de projet": "caractérisation selon critères",
  "importance": "enjeu pour organisation",
  "enjeu": "importance stratégique",
  "innovation": "degré de nouveauté",
  "nouveauté": "aspect innovant",
  "autonomie": "degré liberté décision",
  "complexité": "nombre domaines techniques imbriqués",
  "taille": "périmètre et budget",
  "envergure": "ampleur du projet",
  
  // Types de projets
  "projet historique": "décisions irréversibles",
  "projet récurrent": "processus répétitif",
  "projet unique": "non reproductible",
  "projet innovant": "création nouveauté",
  "projet routinier": "répétitif et connu",
  "projet exploratoire": "recherche et découverte",
  "projet transfo": "transformation organisation",
  
  // Dualité projet-opérations
  "opérations": "permanent et récurrent",
  "processus": "succession activités répétitives",
  "activité continue": "opérations permanentes",
  "activité temporaire": "projet limité temps",
  "organisation temporaire": "structure projet",
  "organisation stable": "structure opérations",
  "système historique": "décisions irréversibles",
  "système récurrent": "cycles répétés",
  
  // Concepts psychologiques
  "locus de contrôle interne": "sentiment responsabilité personnelle",
  "locus de contrôle externe": "attribution causes externes",
  "responsabilité": "obligation assumer conséquences",
  "proactivité": "anticipation plutôt que réaction",
  "réactivité": "réponse rapide aux événements",
  "motivation": "énergie pour atteindre objectifs",
  "engagement": "implication dans le projet",
  "appropriation": "prise en main personnelle",
  
  // Lois et principes
  "loi de Brooks": "ajouter gens retarde projet en retard",
  "paradoxe gestion projet": "moins info quand plus marge manœuvre",
  "principe Pareto": "80/20",
  "loi Murphy": "si ça peut mal tourner ça tournera mal",
  
  // Communication
  "communication": "échange informations",
  "reporting": "compte-rendu régulier",
  "escalade": "remontée problème hiérarchie",
  "transparence": "partage total information",
  "confidentialité": "restriction accès information",
  "canal communication": "moyen transmission info",
  
  // Négociation
  "négociation": "discussion pour accord",
  "compromis": "accord concessions mutuelles",
  "arbitrage": "décision tranchant entre options",
  "arbitrage multiprojets": "priorisation entre plusieurs projets",
  "priorisation": "classement par ordre importance",
  "trade-off": "compromis entre contraintes",
  
  // Cartographie parties prenantes
  "carte parties prenantes": "matrice pouvoir intérêt",
  "pouvoir": "capacité influencer projet",
  "intérêt": "ce qu'acteur gagne ou perd",
  "influenceur": "partie prenante fort pouvoir",
  "bénéficiaire": "partie prenante profitant projet",
  "opposant": "partie prenante contre projet",
  "allié": "partie prenante soutenant projet",
  "engagé": "partie prenante impliquée activement",
  
  // Gestion du changement
  "conduite du changement": "accompagnement transformation",
  "change management": "conduite du changement",
  "résistance au changement": "opposition modifications",
  "accompagnement": "soutien aux acteurs",
  "formation": "transmission compétences",
  "sensibilisation": "prise conscience enjeux",
  
  // Sous-traitance
  "sous-traitance": "délégation partie travaux",
  "externalisation": "recours prestataires externes",
  "outsourcing": "externalisation",
  "appel offres": "procédure sélection prestataire",
  "cahier charges": "spécifications pour appel offres",
  "contrat": "accord juridique contraignant",
  "SLA": "Service Level Agreement",
  "accord niveau service": "SLA",
  "pénalités": "sanctions retard prestataire",
  "clause": "disposition contractuelle",
  
  // Méthodes d'estimation
  "estimation": "évaluation charge ou coût",
  "chiffrage": "estimation détaillée",
  "analogie": "estimation par comparaison",
  "paramétrique": "estimation par formules",
  "bottom-up": "estimation détaillée puis agrégation",
  "top-down": "estimation globale puis répartition",
  "trois points": "estimation pessimiste réaliste optimiste",
  "PERT": "Program Evaluation Review Technique",
  
  // Agilité - concepts détaillés
  "vélocité": "quantité travail par sprint",
  "story": "besoin utilisateur format court",
  "user story": "récit utilisateur",
  "epic": "ensemble stories liées",
  "poker planning": "estimation collective ludique",
  "rétrospective": "bilan amélioration sprint",
  "daily scrum": "réunion quotidienne debout",
  "product owner": "responsable backlog priorisation",
  "scrum master": "facilitateur méthode",
  "développement itératif": "cycles courts amélioration",
  "développement incrémental": "ajouts fonctionnels successifs",
  "amélioration continue": "optimisation permanente",
  "kaizen": "amélioration continue",
  
  // Matrice objectifs
  "matrice objectifs": "grille niveaux performance attendus",
  "insuffisant": "niveau minimal inacceptable",
  "acceptable": "niveau minimal satisfaisant",
  "OK": "niveau conforme attendu",
  "excellent": "niveau dépassant attentes",
  "niveau performance": "degré qualité attendu",
  
  // Check-lists
  "check-list": "liste contrôle systématique",
  "liste contrôle": "check-list",
  "point vigilance": "élément surveiller",
  "bonne pratique": "méthode éprouvée",
  "best practice": "bonne pratique",
  "standard": "référence commune",
  "norme": "règle officielle",
  "procédure": "suite actions définies",
  
  // WBS détails
  "organigramme tâches": "WBS",
  "décomposition": "division en éléments",
  "analyse": "décomposition éléments constituants",
  "synthèse": "regroupement éléments",
  "agrégation": "synthèse",
  "niveau WBS": "profondeur décomposition",
  "tâche élémentaire": "tâche non divisible",
  "tâche sommaire": "regroupement sous-tâches",
  "logique découpage": "critère décomposition",
  "découpage fonctionnel": "par fonctions livrables",
  "découpage métier": "par corps métiers",
  "découpage géographique": "par localisation",
  "découpage temporel": "par phases chronologiques",
  
  // Suivi et pilotage
  "tableau bord": "synthèse indicateurs clés",
  "dashboard": "tableau bord",
  "suivi": "contrôle régulier avancement",
  "monitoring": "suivi",
  "contrôle": "vérification conformité",
  "surveillance": "observation continue",
  "veille": "surveillance environnement",
  "alerte": "signal dépassement seuil",
  "seuil": "limite déclenchement action",
  "point attention": "élément surveiller",
  
  // Actions correctives
  "action corrective": "correction écart constaté",
  "action préventive": "anticipation problème potentiel",
  "mesure": "action mise en œuvre",
  "remédiation": "correction problème",
  "ajustement": "modification légère",
  "recalage": "remise objectifs réalistes",
  "réorientation": "changement direction",
  "pivot": "changement stratégique majeur",
  
  // Clôture projet
  "dissolution équipe": "fin collaboration projet",
  "réaffectation": "nouvelle affectation personnes",
  "archivage": "conservation documents",
  "transfert compétences": "transmission savoir",
  "passation": "transfert responsabilités",
  "documentation finale": "dossier clôture complet",
  "garantie": "engagement post-livraison",
  "maintenance": "entretien après livraison",
  "support": "assistance utilisateurs",
  "hotline": "support technique",
  
  // Innovation et créativité
  "créativité": "génération idées nouvelles",
  "idéation": "génération idées",
  "prototypage": "création prototypes",
  "expérimentation": "tests essais",
  
  // Gestion configuration
  "configuration": "état défini du livrable",
}